### ISSUE TITLE
[error] unresolved dependency: com.github.scct#scct;0.3-SNAPSHOT: not found

### ISSUE THREAD

**Issue by taylorleese** [sqality/scct#19]
I haven't been able to resolve 0.3-SNAPSHOT or 0.2. I get similar errors for both sbt 0.12.4 and 0.13.0. This is the error:

``` shell
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      com.github.scct:scct:0.3-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10)
...
[error] unresolved dependency: com.github.scct#scct;0.3-SNAPSHOT: not found
```

**Comment by 0xRoch** [comment]
@taylorleese did you import the Sonatype Snapshot repository ? 
`resolvers += "Sonatype OSS" at "https://oss.sonatype.org/content/repositories/snapshots"`

The deps you talk about are published here : 
https://oss.sonatype.org/content/repositories/snapshots/com/github/scct/sbt-scct_2.10_0.13/
Let me know if it solves your problem.

**Comment by taylorleese** [comment]
Actually, I had the artifact name wrong -- scct instead of sbt-scct.

**Comment by 0xRoch** [comment]
@taylorleese great does it solve your previous issue ?

**Comment by taylorleese** [comment]
@D-Roch No, I still get the same error reported in #6 with 0.3-SNAPSHOT.
