### ISSUE TITLE
Unable to retrieve SNAPSHOT version - no maven-metadata.xml

### ISSUE THREAD

**Issue by Laura-M** [sqality/scct#20]
When I try to retrieve the latest SNAPSHOT version from the Sonatype repo in my SBT build, I receive an error when trying to retrieve the maven-metadata.xml file (and indeed, it doesn't exist). I believe this file is required in order to find the snapshot, as detailed in this post:

https://groups.google.com/forum/#!msg/simple-build-tool/okaoV3SDH24/P9NJZF67Hq0J

I can retrieve the released versions without issue, unfortunately, when I use these I encounter some errors. I have successfully run SCCT using a snapshot version built from the latest source, so would like to be able to use the snapshot. Can the maven-metadata.xml file be added as part of the snapshot deployment?

Forgive me if this is not an issue and I am missing something obvious here, I'm a bit of an SBT novice.

**Comment by 0xRoch** [comment]
@Laura-M we had a few issues with the 0.2-SNAPSHOT disappearing, as you can see here: https://oss.sonatype.org/content/repositories/snapshots/com/github/scct/scct_2.9.2/0.3-SNAPSHOT/ the maven-metadata.xml is included in the snapshot publishing. Could you please confirm which version you are using ?
You can use 0.3-SNAPSHOT instead or the last release : 0.2.1

**Comment by Laura-M** [comment]
@D-Roch I'm using the (Scala 2.10, SBT 0.13) 0.3-SNAPSHOT version from here: http://oss.sonatype.org/content/repositories/snapshots/com/github/scct/sbt-scct_2.10_0.13/0.3-SNAPSHOT/ which doesn't appear to have the maven-metadata.xml file included. I can definitely see it in the 2.9.2 version though.

**Comment by 0xRoch** [comment]
Hi @Laura-M 
How do you import the deps in your project ?
Adding the following code in your project/plugins.sbt should be fine : 

```
resolvers += "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"

addSbtPlugin("com.github.scct" % "sbt-scct" % "0.3-SNAPSHOT")
```

Have a look at the sample scct project if you need : https://github.com/SCCT/scctSample/blob/master/project/plugins.sbt

**Comment by 0xRoch** [comment]
A new version has been released you can use it using : 

addSbtPlugin("com.github.scct" % "sbt-scct" % "0.3")
